# Generated by Django 4.2.3 on 2023-07-26 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ordinal', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia', to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1)),
                ('fecha_nacimiento', models.DateField(default=datetime.date(2000, 1, 1))),
                ('anteojos', models.CharField(max_length=10)),
                ('estado', models.IntegerField(choices=[(0, 'Sin estado'), (1, 'Activo'), (2, 'Suspendido'), (3, 'Suspendido')], default=0)),
                ('dominio_ingles', models.IntegerField(choices=[(0, 'Sin estado'), (1, 'Básico'), (2, 'Medio'), (3, 'Avanzado'), (4, 'Nativo')], default=0)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='core.comuna')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna', to='core.provincia'),
        ),
    ]
