# Generated by Django 4.2.3 on 2023-07-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='persona_id',
            new_name='id',
        ),
    ]
